source: https://api.mews.com/swagger/connector/swagger.yaml
output: ../operations
tags:
  # - accountingcategories
  # - accountingitems
  - accountnotes
  # - accounts
  # - addresses
  # - agecategories
  - availabilityadjustments
  # - availabilityblocks
  # - bills
  # - businesssegments
  - cancellationpolicies
  # - cashiers
  # - cashiertransactions
  # - commands
  - companies
  # - companionships
  # - companycontracts
  # - configuration
  # - counters
  - countries
  # - creditcards
  - currencies
  # - customers
  # - departments
  - devices
  # - enterprises
  - exchangerates
  - exports
  - images
  # - languages
  # - loyaltymemberships
  # - loyaltyprograms
  # - loyaltytiers
  # - messages
  # - messagethreads
  - orderitems
  # - orders
  # - outletbills
  - outletitems
  # - outlets
  # - paymentrequests
  # - payments
  # - preauthorizations
  # - productcategories
  # - products
  # - productserviceorders
  # - rategroups
  # - rates
  # - reservationgroups
  - reservations
  # - resourceaccesstokens
  # - resourceblocks
  # - resourcecategories
  # - resourcefeatures
  # - resources
  # - restrictions
  # - routingrules
  # - rules
  # - serviceordernotes
  - services
  # - sourceassignments
  - sources
  # - tasks
  # - taxations
  # - taxenvironments
  - vouchercodes
  - vouchers
